bookmark.ActiveDesktop=F\:\\ActiveDesktop
bookmark.ActiveDownloads=F\:\\ActiveDownloads
bookmark.Movies=F\:\\Downloaded_movies\\Movies
ftp.haifa.host=51.38.67.129
ftp.haifa.password=chaiavi77&
ftp.haifa.port=21
ftp.haifa.username=temp@haifaport.com
ftp.movie.host=51.38.67.129
ftp.movie.password=chaiavi77&
ftp.movie.port=21
ftp.movie.username=temp@chaimovie.com
left_folder=C\:\\
right_folder=C\:\\
theme_mode=regular
