bookmark.ActiveDesktop=F\:\\ActiveDesktop
bookmark.ActiveDownloads=F\:\\ActiveDownloads
bookmark.Movies=F\:\\Downloaded_movies\\Movies
ftp.haifa.host=51.38.67.129
ftp.haifa.password=chaiavi77&
ftp.haifa.port=21
ftp.haifa.username=temp@haifaport.com
left_folder=/folderfolder
right_folder=F\:\\ActiveDesktop\\1111111111\\1234
theme_mode=regular
